from typing import Optional


MCTS_SIMULATIONS = 80  #
MCTS_ITERATIONS = 20  #
MCTS_TIME_BUDGET = 1  #
SCORE_3_ERRORS: float = 0  # NB: SCORE_3_ERRORS MUST BE A FLOAT, WHICH WILL BE MULTIPLIED * sum(board)
RULE_9_BEST_IDX_0: bool = False  # NB: if RULE_9_BEST_IDX_0 is False, instead will be used FUR (First Unknown Rank)
PLAY_SAFE_PROBABILITY = 0.7  #
PLAY_SAFE_LATE_PROBABILITY = 0.4  #
DISCARD_PROBABILITY = 0.7  #
